americanfootball_nfl:
    - feature_market_spreads
    - additional_markets
    - game_period_markets_basketball_football
    - american_football_player_props
    - alternative_football_player_props
americanfootball_ncaaf:
    - feature_market_spreads
    - additional_markets
    - game_period_markets_basketball_football
    - american_football_player_props
    - alternative_football_player_props
basketball_nba:
    - feature_market_spreads
    - additional_markets
    - game_period_markets_basketball_football
    - basketball_player_props
    - alternative_basketball_player_props
icehockey_nhl:
    - feature_market_spreads
    - additional_markets
    - game_period_markets_hockey
    - hockey_player_props
    - alternative_hockey_player_props
baseball_mlb:
    - feature_market_spreads
    - additional_markets
    - game_period_markets_baseball
    - baseball_player_props
    - alternative_baseball_player_props
basketball_ncaab:
    - feature_market_spreads
    - additional_markets
    - game_period_markets_ncaa_basketball
    - basketball_player_props
    - alternative_basketball_player_props
    
