feature_market_spreads:
    h2h: 'Moneyline; Bet on the winning team or player of a game (includes the draw for soccer)'
    spreads: 'The spreads market as featured by a bookmaker. Bet on the winning team after a points handicap has been applied to each team'
    totals: 'The totals market as featured by a bookmaker. Bet on the total score of the game being above or below a threshold'
    outrights: 'Bet on a final outcome of a tournament or competition'
    h2h_lay: 'Bet against a h2h outcome. This market is only applicable to betting exchanges'
    outrights_lay: 'Bet against an outrights outcome. This market is only applicable to betting exchanges'
additional_markets:
    alternate_spreads: 'All available point spread outcomes for each team'
    alternate_totals: 'All available over/under outcomes'
    btts: 'Both Teams to Score - Odds that both teams will score during the game. Outcomes are binary: Yes or No or No. Available for soccer.'
    draw_no_bet: 'Odds for the match winner, excluding the draw outcome. A draw will result in a returned bet. Available for soccer'
    h2h_3_way: 'Match winner including draw'
    team_totals: 'Featured team totals (Over/Under)'
    alternate_team_totals: 'All available team totals (Over/Under)'
game_period_markets:
    h2h_q1: 'Moneyline 1st Quarter'
    h2h_q2: 'Moneyline 2nd Quarter'
    h2h_q3: 'Moneyline 3rd Quarter'
    h2h_q4: 'Moneyline 4th Quarter'
    h2h_h1: 'Moneyline 1st Half'
    h2h_h2: 'Moneyline 2nd Half'
    h2h_p1: 'Moneyline 1st Period - Valid for ice hockey'
    h2h_p2: 'Moneyline 2nd Period	Valid for ice hockey'
    h2h_p3: 'Moneyline 3rd Period	Valid for ice hockey'
    h2h_1st_1_innings: 'Moneyline 1st inning Valid for baseball'
    h2h_1st_3_innings: 'Moneyline 1st 3 innings	Valid for baseball'
    h2h_1st_5_innings: 'Moneyline 1st 5 innings	Valid for baseball'
    h2h_1st_7_innings: 'Moneyline 1st 7 innings	Valid for baseball'
    h2h_3_way_1st_1_innings: '3-way moneyline 1st inning	Valid for baseball'
    h2h_3_way_1st_3_innings: '3-way moneyline 1st 3 innings	Valid for baseball'
    h2h_3_way_1st_5_innings: '3-way moneyline 1st 5 innings	Valid for baseball'
    h2h_3_way_1st_7_innings: '3-way moneyline 1st 7 innings	Valid for baseball'
    spreads_q1: 'Spreads 1st Quarter'
    spreads_q2: 'Spreads 2nd Quarter'
    spreads_q3: 'Spreads 3rd Quarter'
    spreads_q4: 'Spreads 4th Quarter'
    spreads_h1: 'Spreads 1st Half'
    spreads_h2: 'Spreads 2nd Half'
    spreads_p1: 'Spreads 1st Period	Valid for ice hockey'
    spreads_p2: 'Spreads 2nd Period	Valid for ice hockey'
    spreads_p3: 'Spreads 3rd Period	Valid for ice hockey'
    spreads_1st_1_innings: 'Spreads 1st inning Valid for baseball'
    spreads_1st_3_innings: 'Spreads 1st 3 innings Valid for baseball'
    spreads_1st_5_innings: 'Spreads 1st 5 innings Valid for baseball'
    spreads_1st_7_innings: 'Spreads 1st 7 innings Valid for baseball'
    alternate_spreads_1st_1_innings: 'Alternate spreads 1st inning Valid for baseball'
    alternate_spreads_1st_3_innings: 'Alternate spreads 1st 3 innings Valid for baseball'
    alternate_spreads_1st_5_innings: 'Alternate spreads 1st 5 innings Valid for baseball'
    alternate_spreads_1st_7_innings: 'Alternate spreads 1st 7 innings Valid for baseball'
    alternate_spreads_q1: 'Alternate spreads Q1'
    alternate_spreads_h1: 'Alternate spreads H1'
    totals_q1: 'Over/under 1st Quarter'
    totals_q2: 'Over/under 2nd Quarter'
    totals_q3: 'Over/under 3rd Quarter'
    totals_q4: 'Over/under 4th Quarter'
    totals_h1: 'Over/under 1st Half'
    totals_h2: 'Over/under 2nd Half'
    totals_p1: 'Over/under 1st Period Valid for ice hockey'
    totals_p2: 'Over/under 2nd Period Valid for ice hockey'
    totals_p3: 'Over/under 3rd Period Valid for ice hockey'
    totals_1st_1_innings: 'Over/under 1st inning Valid for baseball'
    totals_1st_3_innings: 'Over/under 1st 3 innings	Valid for baseball'
    totals_1st_5_innings: 'Over/under 1st 5 innings	Valid for baseball'
    totals_1st_7_innings: 'Over/under 1st 7 innings	Valid for baseball'
    alternate_totals_1st_1_innings: 'Alternate over/under 1st inning	Valid for baseball'
    alternate_totals_1st_3_innings: 'Alternate over/under 1st 3 innings	Valid for baseball'
    alternate_totals_1st_5_innings: 'Alternate over/under 1st 5 innings	Valid for baseball'
    alternate_totals_1st_7_innings: 'Alternate over/under 1st 7 innings	Valid for baseball'
    alternate_totals_q1: 'Alternate totals Q1'
    alternate_totals_h1: 'Alternate totals H1'
    team_totals_h1: 'Team Totals H1'
    team_totals_h2: 'Team Totals H2'
    team_totals_q1: 'Team Totals Q1'
    team_totals_q2: 'Team Totals Q2'
    team_totals_q3: 'Team Totals Q3'
    team_totals_q4: 'Team Totals Q4'
    alternate_team_totals_h1: 'Alternate team totals H1'
    alternate_team_totals_h2: 'Alternate team totals H2'
american_football_player_props:
    player_field_goals: 'Field Goals (Over/Under)'
    player_kicking_points: 'Kicking Points (Over/Under)'
    player_pass_attempts: 'Pass Attempts (Over/Under)'
    player_pass_completions: 'Pass Completions (Over/Under)'
    player_pass_interceptions: 'Pass Intercepts (Over/Under)'
    player_pass_longest_completion: 'Longest Pass Completion (Over/Under)'
    player_pass_rush_reception_tds: 'Pass + Rush + Reception Touchdowns (Over/Under)'
    player_pass_rush_reception_yds: 'Pass + Rush + Reception Yards (Over/Under)'
    player_pass_tds: 'Pass Touchdowns (Over/Under)'
    player_pass_yds: 'Pass Yards (Over/Under)'
    player_pats: 'Points After Touchdown (Over/Under)'
    player_receptions: 'Receptions (Over/Under)'
    player_reception_longest: 'Longest Reception (Over/Under)'
    player_reception_yds: 'Reception Yards (Over/Under)'
    player_rush_attempts: 'Rush Attempts (Over/Under)'
    player_rush_longest: 'Longest Rush (Over/Under)'
    player_rush_reception_tds: 'Rush + Reception Touchdowns (Over/Under)'
    player_rush_reception_yds: 'Rush + Reception Yards (Over/Under)'
    player_rush_yds: 'Rush Yards (Over/Under)'
    player_sacks: 'Sacks (Over/Under)'
    player_solo_tackles: 'Solo Tackles (Over/Under)'
    player_tackles_assists: 'Tackles + Assists (Over/Under)'
    player_tds_over_touchdowns: 'Touchdowns Over only'
    player_1st_td: '1st Touchdown Scorer (Yes/No)'
    player_anytime_td: 'Anytime Touchdown Scorer (Yes/No)'
    player_last_td: 'Last Touchdown Scorer (Yes/No)'
alternative_football_player_props:
    player_assists_alternate: 'Alternate Assists (Over/Under)'
    player_field_goals_alternate: 'Alternate Field Goals (Over/Under)'
    player_kicking_points_alternate: 'Alternate Kicking Points (Over/Under)'
    player_pass_attempts_alternate: 'Alternate Pass Attempts (Over/Under)'
    player_pass_completions_alternate: 'Alternate Pass Completions (Over/Under)'
    player_pass_interceptions_alternate: 'Alternate Pass Interceptions (Over/Under)'
    player_pass_longest_completion_alternate: 'Alternate Longest Pass Completion (Over/Under)'
    player_pass_rush_reception_tds_alternate: 'Alternate Pass + Rush + Reception Touchdowns (Over/Under)'
    player_pass_rush_reception_yds_alternate: 'Alternate Pass + Rush + Reception Yards (Over/Under)'
    player_pass_tds_alternate: 'Alternate Pass Touchdowns (Over/Under)'
    player_pass_yds_alternate: 'Alternate Pass Yards (Over/Under)'
    player_pats_alternate: 'Alternate Points After Touchdown (Over/Under)'
    player_receptions_alternate: 'Alternate Receptions (Over/Under)'
    player_reception_longest_alternate: 'Alternate Longest Reception (Over/Under)'
    player_reception_yds_alternate: 'Alternate Reception Yards (Over/Under)'
    player_rush_attempts_alternate: 'Alternate Rush Attempts (Over/Under)'
    player_rush_longest_alternate: 'Alternate Longest Rush (Over/Under)'
    player_rush_reception_tds_alternate: 'Alternate Rush + Reception Touchdowns (Over/Under)'
    player_rush_reception_yds_alternate: 'Alternate Rush + Reception Yards (Over/Under)'
    player_rush_yds_alternate: 'Alternate Rush Yards (Over/Under)'
    player_sacks_alternate:  'Alternate Sacks (Over/Under)'
    player_solo_tackles_alternate: 'Alternate Solo Tackles (Over/Under)'
    player_tackles_assists_alternate: 'Alternate Tackles + Assists (Over/Under)'
basketball_player_props:
    player_points: 'Points (Over/Under)'
    player_rebounds: 'Rebounds (Over/Under)'
    player_assists: 'Assists (Over/Under)'
    player_threes: 'Threes (Over/Under)'
    player_blocks: 'Blocks (Over/Under)'
    player_steals: 'Steals (Over/Under)'
    player_blocks_steals: 'Blocks + Steals (Over/Under)'
    player_turnovers: 'Turnovers (Over/Under)'
    player_points_rebounds_assists: 'Points + Rebounds + Assists (Over/Under)'
    player_points_rebounds: 'Points + Rebounds (Over/Under)'
    player_points_assists: 'Points + Assists (Over/Under)'
    player_rebounds_assists: 'Rebounds + Assists (Over/Under)'
    player_first_basket: 'First Basket Scorer (Yes/No)'
    player_double_double: 'Double Double (Yes/No)'
    player_triple_double: 'Triple Double (Yes/No)'
    alternative_basketball_player_props:
    player_points_alternate: 'Alternate Points (Over/Under)'
    player_rebounds_alternate: 'Alternate Rebounds (Over/Under)'
    player_assists_alternate: 'Alternate Assists (Over/Under)'
    player_blocks_alternate: 'Alternate Blocks (Over/Under)'
    player_steals_alternate: 'Alternate Steals (Over/Under)'
    player_threes_alternate: 'Alternate Threes (Over/Under)'
    player_points_assists_alternate: 'Alternate Points + Assists (Over/Under)'
    player_points_rebounds_alternate: 'Alternate Points + Rebounds (Over/Under)'
    player_rebounds_assists_alternate: 'Alternate Rebounds + Assists (Over/Under)'
    player_points_rebounds_assists_alternate: 'Alternate Points + Rebounds + Assists (Over/Under)'
baseball_player_props:
    batter_home_runs: 'Batter home runs (Over/Under)'
    batter_first_home_run: 'Batter first home run (Yes/No)'
    batter_hits: 'Batter hits (Over/Under)'
    batter_total_bases: 'Batter total bases (Over/Under)'
    batter_rbis_batter: 'RBIs (Over/Under)'
    batter_runs_scored: 'Batter runs scored (Over/Under)'
    batter_hits_runs_rbis: 'Batter hits + runs + RBIs (Over/Under)'
    batter_singles: 'Batter singles (Over/Under)'
    batter_doubles: 'Batter doubles (Over/Under)'
    batter_triples: 'Batter triples (Over/Under)'
    batter_walks: 'Batter walks (Over/Under)'
    batter_strikeouts: 'Batter strikeouts (Over/Under)'
    batter_stolen_bases: 'Batter stolen bases (Over/Under)'
    pitcher_strikeouts: 'Pitcher strikeouts (Over/Under)'
    pitcher_record_a_win: 'Pitcher to record a win (Yes/No)'
    pitcher_hits_allowed: 'Pitcher hits allowed (Over/Under)'
    pitcher_walks: 'Pitcher walks (Over/Under)'
    pitcher_earned_runs: 'Pitcher earned runs (Over/Under)'
    pitcher_outs: 'Pitcher outs (Over/Under)'
alternative_baseball_player_props:
    batter_total_bases_alternate: 'Alternate batter total bases (Over/Under)'
    batter_home_runs_alternate: 'Alternate batter home runs (Over/Under)'
    batter_hits_alternate: 'Alternate batter hits (Over/Under)'
    batter_rbis_alternate: 'Alternate batter RBIs (Over/Under)'
    pitcher_hits_allowed_alternate: 'Alternate pitcher hits allowed (Over/Under)'
    pitcher_walks_alternate: 'Alternate pitcher walks allowed (Over/Under)'
    pitcher_strikeouts_alternate: 'Alternate pitcher strikeouts (Over/Under)'
hockey_player_props:
    player_points: 'Points (Over/Under)'
    player_power_play_points: 'Power play points (Over/Under)'
    player_assists: 'Assists (Over/Under)'
    player_blocked_shots: 'Blocked shots (Over/Under)'
    player_shots_on_goal: 'Shots on goal (Over/Under)'
    player_goals: 'Goals (Over/Under)'
    player_total_saves: 'Total saves (Over/Under)'
    player_goal_scorer_first: 'First Goal Scorer (Yes/No)'
    player_goal_scorer_last: 'Last Goal Scorer (Yes/No)'
    player_goal_scorer_anytime: 'Anytime Goal Scorer (Yes/No)'
alternative_hockey_player_props:
    player_points_alternate: 'Alternate Points (Over/Under)'
    player_assists_alternate: 'Alternate Assists (Over/Under)'
    player_power_play_points_alternate: 'Alternate Power Play Points (Over/Under)'
    player_goals_alternate: 'Alternate Goals (Over/Under)'
    player_shots_on_goal_alternate: 'Alternate Shots on Goal (Over/Under)'
    player_blocked_shots_alternate: 'Alternate Blocked Shots (Over/Under)'
    player_total_saves_alternate: 'Alternate Total Saves (Over/Under)'
australian_football_league_player_props: 
    player_disposals: 'Disposals (Over/Under)'
    player_disposals_over: 'Disposals (Over only)'
    player_goal_scorer_first: 'First Goal Scorer (Yes/No)'
    player_goal_scorer_last: 'Last Goal Scorer (Yes/No)'
    player_goal_scorer_anytime: 'Anytime Goal Scorer (Yes/No)'
    player_goals_scored_over: 'Goals scored (Over only)'
    player_marks_over: 'Marks (Over only)'
    player_marks_most: 'Most Marks (Yes/No)'
    player_tackles_over: 'Tackles (Over only)'
    player_tackles_most: 'Tackles (Yes/No)'
    player_afl_fantasy_points: 'AFL Fantasy Points (Over/Under)' 
    player_afl_fantasy_points_over: 'AFL Fantasy Points (Over only)'
    player_afl_fantasy_points_most: 'Most AFL Fantasy Points (Yes/No)'
rugby_player_props:
    player_try_scorer_first: 'First Try Scorer (Yes/No)'
    player_try_scorer_last: 'Last Try Scorer (Yes/No)'
    player_try_scorer_anytime: 'Anytime Try Scorer (Yes/No)'
    player_try_scorer_over: 'Tries Scored (Over only)'
soccer_player_props:
    player_goal_scorer_anytime: 'Anytime Goal Scorer (Yes/No)'
    player_first_goal_scorer: 'First Goal Scorer (Yes/No)'
    player_last_goal_scorer: 'Last Goal Scorer (Yes/No)'
    player_to_receive_card: 'Player to receive a card (Yes/No)'
    player_to_receive_red_card: 'Player to receive a red card (Yes/No)'
    player_shots_on_target: 'Player Shots on Target (Over/Under)'
    player_shots: 'Player Shots (Over/Under)'
    player_assists: 'Player Assists (Over/Under)'
alternative_soccer_props:
    alternate_spreads_corners: 'Handicap Corners'
    alternate_totals_corners: 'Total Corners (Over/Under)'
    alternate_spreads_cards: 'Handicap Cards / Bookings'
    alternate_totals_cards: 'Total Cards / Bookings (Over/Under)'
    double_chance: 'Double Chance'


