american_football:
    americanfootball_ncaaf: 'US College Football'
    americanfootball_ncaaf_championship_winner: 'NCAAF Championship Winner'
    americanfootball_nfl: 'NFL'
    americanfootball_nfl_super_bowl_winner: 'NFL Super Bowl Winner'
austrialian_football:
    aussierules_afl: 'AFL'
rugby:
    rugbyleague_nrl: 'NRL'
basketball:
    basketball_nba: 'NBA'
    basketball_nba_championship_winner: 'NBA Championship Winner'
    basketball_nbl: 'NBL',
    basketball_ncaab: 'NCAA Basketball'
    basketball_ncaab_championship_winner: "NCAAB Championship Winner"
    basketball_wncaab: "WNCAA Basketball"
combat:
    boxing_boxing: "Boxing"
    mma_mixed_martial_arts: "Mixed Martial Arts"
cricket: 
    cricket_international_t20: 'Cricket International Twenty20'
    cricket_test_match: 'Cricket International Test Matches'
    
golf:
    golf_masters_tournament_winner: 'Masters Tournament Winner'
    golf_pga_championship_winner: 'PGA Championship Winner'
hockey:
    icehockey_nhl: 'NHL'
    icehockey_nhl_championship_winner: 'Stanley Cup Winner'
    icehockey_sweden_allsvenskan: 'Swedish Hockey Allsvenskan'
    icehockey_sweden_hockey_league: 'Swedish Hockey League'
soccer: 
    soccer_argentina_primera_division: 'Primera Division - Argentina'
    soccer_australia_aleague: 'Aussie Soccer'
    soccer_austria_bundesliga: 'Austrian Soccer'  
    soccer_belgium_first_div: 'Belgian First Division A'
    soccer_brazil_campeonato: 'Campeonato Brasileiro Serie A'
    soccer_conmebol_copa_libertadores: 'CONMEBOL Copa Libertadores'
    soccer_denmark_superliga: 'Danish Soccer'
    soccer_efl_champ: 'EFL Championship'
    soccer_england_league1: 'EFL League 1'
    soccer_england_league2: 'EFL League 2'
    soccer_epl: 'English Premier League'
    soccer_fa_cup: 'Football Association Challenge Cup'
    soccer_fifa_world_cup_winner: 'FIFA World Cup Winner'
    soccer_france_ligue_one: 'Ligue 1 - France'
    soccer_france_ligue_two: 'Ligue 2 - France'
    soccer_germany_bundesliga: 'Bundesliga - Germany'
    soccer_germany_bundesliga2: 'Bundesliga 2 - Germany'
    soccer_germany_liga3: '3. Liga - Germany'
    soccer_greece_super_league: 'Super League - Greece'
    soccer_italy_serie_a: 'Serie A - Italy'
    soccer_italy_serie_b: 'Serie B - Italy'
    soccer_japan_j_league: 'Japan Soccer League'
    soccer_korea_kleague1: 'Korean Soccer'
    soccer_league_of_ireland: 'Airtricity League Premier Division'
    soccer_mexico_ligamx: 'Mexican Soccer'
    soccer_netherlands_eredivisie: 'Dutch Soccer'
    soccer_norway_eliteserien: 'Norwegian Soccer'
    soccer_poland_ekstraklasa: 'Polish Soccer'
    soccer_portugal_primeira_liga: 'Portugese Soccer'
    soccer_spain_la_liga: 'La Liga - Spain'
    soccer_spain_segunda_division: 'La Liga 2 - Spain'
    soccer_spl: 'Scottish Premiership'
    soccer_switzerland_superleague: 'Swiss Soccer'
    soccer_turkey_super_league: 'Turkish Soccer'
    soccer_uefa_champs_league: 'UEFA Champions League'
    soccer_usa_mls: '"Major League Soccer'